numbers = {
    1 : "one",
    2 : "two",
    3 : "three",
    4 : "four",
    5 : "five",
    6 : "six",
    7 : "seven",
    8 : "eight",
    9 : "nine",
    10 : "ten",
    11 : "eleven",
    12 : "twelve",
    13 : "thirteen",
    14 : "foruteen",
    15 : "fifteen",
    16 : "sixteen",
    17 : "seventeen",
    18 : "eighteen",
    19 : "nineteen",
    20 : "twenty",
    21 : "twenty-one",
    22 : "twenty-two",
    23 : "twenty-three",
    24 : "twenty-four",
    25 : "twenty-five",
    26 : "twenty-six",
    27 : "twenty-seven",
    28 : "twenty-eight",
    29 : "twenty-nine",
    30 : "thirty",
    31 : "thirty-one",
    32 : "thirty-two",
    33 : "thirty-three",
    34 : "thirty-four",
    35 : "thirty-five",
    36 : "thirty-six",
    37 : "thirty-seven",
    38 : "thirty-eight",
    39 : "thirty-nine",
    40 : "forty",
    41 : "forty-one",
    42 : "forty-two",
    43 : "forty-three",
    44 : "forty-four",
    45 : "forty-five",
    46 : "forty-six",
    47 : "forty-seven",
    48 : "forty-eight",
    49 : "forty-nine",
    50 : "fifty",
    51 : "fifty-one",
    52 : "fifty-two",
    53 : "fifty-three",
    54 : "fifty-four",
    55 : "fifty-five",
    56 : "fifty-six",
    57 : "fifty-seven",
    58 : "fifty-eight",
    59 : "fifty-nine",
    60 : "sixty",
    61 : "sixty-one",
    62 : "sixty-two",
    63 : "sixty-three",
    64 : "sixty-four",
    65 : "sixty-five",
    66 : "sixty-six",
    67 : "sixty-seven",
    68 : "sixty-eight",
    69 : "sixty-nine",
    70 : "seventy",
    71 : "seventy-one",
    72 : "seventy-two",
    73 : "seventy-three",
    74 : "seventy-four",
    75 : "seventy-five",
    76 : "seventy-six",
    77 : "seventy-seven",
    78 : "seventy-eight",
    79 : "seventy-nine",
    80 : "eighty",
    81 : "eighty-one",
    82 : "eighty-two",
    83 : "eighty-three",
    84 : "eighty-four",
    85 : "eighty-five",
    86 : "eighty-six",
    87 : "eighty-seven",
    88 : "eighty-eight",
    89 : "eighty-nine",
    90 : "ninety",
    91 : "ninety-one",
    92 : "ninety-two",
    93 : "ninety-three",
    94 : "ninety-four",
    95 : "ninety-five",
    96 : "ninety-six",
    97 : "ninety-seven",
    98 : "ninety-eight",
    99 : "ninety-nine",
    100 : "one hundred",
    101 : "one hundred one",
    102 : "one hundred two",
    103 : "one hundred three",
    104 : "one hundred four",
    105 : "one hundred five",
    106 : "one hundred six",
    107 : "one hundred seven",
    108 : "one hundred eight",
    109 : "one hundred nine",
    110 : "one hundred ten",
    111 : "one hundred eleven",
    112 : "one hundred twelve",
    113 : "one hundred thirteen",
    114 : "one hundred foruteen",
    115 : "one hundred fifteen",
    116 : "one hundred sixteen",
    117 : "one hundred seventeen",
    118 : "one hundred eighteen",
    119 : "one hundred nineteen",
    120 : "one hundred twenty",
    121 : "one hundred twenty-one",
    122 : "one hundred twenty-two",
    123 : "one hundred twenty-three",
    124 : "one hundred twenty-four",
    125 : "one hundred twenty-five",
    126 : "one hundred twenty-six",
    127 : "one hundred twenty-seven",
    128 : "one hundred twenty-eight",
    129 : "one hundred twenty-nine",
    130 : "one hundred thirty",
    131 : "one hundred thirty-one",
    132 : "one hundred thirty-two",
    133 : "one hundred thirty-three",
    134 : "one hundred thirty-four",
    135 : "one hundred thirty-five",
    136 : "one hundred thirty-six",
    137 : "one hundred thirty-seven",
    138 : "one hundred thirty-eight",
    139 : "one hundred thirty-nine",
    140 : "one hundred forty",
    141 : "one hundred forty-one",
    142 : "one hundred forty-two",
    143 : "one hundred forty-three",
    144 : "one hundred forty-four",
    145 : "one hundred forty-five",
    146 : "one hundred forty-six",
    147 : "one hundred forty-seven",
    148 : "one hundred forty-eight",
    149 : "one hundred forty-nine",
    150 : "one hundred fifty",
    151 : "one hundred fifty-one",
    152 : "one hundred fifty-two",
    153 : "one hundred fifty-three",
    154 : "one hundred fifty-four",
    155 : "one hundred fifty-five",
    156 : "one hundred fifty-six",
    157 : "one hundred fifty-seven",
    158 : "one hundred fifty-eight",
    159 : "one hundred fifty-nine",
    160 : "one hundred sixty",
    161 : "one hundred sixty-one",
    162 : "one hundred sixty-two",
    163 : "one hundred sixty-three",
    164 : "one hundred sixty-four",
    165 : "one hundred sixty-five",
    166 : "one hundred sixty-six",
    167 : "one hundred sixty-seven",
    168 : "one hundred sixty-eight",
    169 : "one hundred sixty-nine",
    170 : "one hundred seventy",
    171 : "one hundred seventy-one",
    172 : "one hundred seventy-two",
    173 : "one hundred seventy-three",
    174 : "one hundred seventy-four",
    175 : "one hundred seventy-five",
    176 : "one hundred seventy-six",
    177 : "one hundred seventy-seven",
    178 : "one hundred seventy-eight",
    179 : "one hundred seventy-nine",
    180 : "one hundred eighty",
    181 : "one hundred eighty-one",
    182 : "one hundred eighty-two",
    183 : "one hundred eighty-three",
    184 : "one hundred eighty-four",
    185 : "one hundred eighty-five",
    186 : "one hundred eighty-six",
    187 : "one hundred eighty-seven",
    188 : "one hundred eighty-eight",
    189 : "one hundred eighty-nine",
    190 : "one hundred ninety",
    191 : "one hundred ninety-one",
    192 : "one hundred ninety-two",
    193 : "one hundred ninety-three",
    194 : "one hundred ninety-four",
    195 : "one hundred ninety-five",
    196 : "one hundred ninety-six",
    197 : "one hundred ninety-seven",
    198 : "one hundred ninety-eight",
    199 : "one hundred ninety-nine",
    200 : "two hundred",
    201 : "two hundred one",
    202 : "two hundred two",
    203 : "two hundred three",
    204 : "two hundred four",
    205 : "two hundred five",
    206 : "two hundred six",
    207 : "two hundred seven",
    208 : "two hundred eight",
    209 : "two hundred nine",
    210 : "two hundred ten",
    211 : "two hundred eleven",
    212 : "two hundred twelve",
    213 : "two hundred thirteen",
    214 : "two hundred fourteen",
    215 : "two hundred fifteen",
    216 : "two hundred sixteen",
    217 : "two hundred seventeen",
    218 : "two hundred eighteen",
    219 : "two hundred nineteen",
    220 : "two hundred twenty",
    221 : "two hundred twenty-one",
    222 : "two hundred twenty-two",
    223 : "two hundred twenty-three",
    224 : "two hundred twenty-four",
    225 : "two hundred twenty-five",
    226 : "two hundred twenty-six",
    227 : "two hundred twenty-seven",
    228 : "two hundred twenty-eight",
    229 : "two hundred twenty-nine",
    230 : "two hundred thirty",
    231 : "two hundred thirty-one",
    232 : "two hundred thirty-two",
    233 : "two hundred thirty-three",
    234 : "two hundred thirty-four",
    235 : "two hundred thirty-five",
    236 : "two hundred thirty-six",
    237 : "two hundred thirty-seven",
    238 : "two hundred thirty-eight",
    239 : "two hundred thirty-nine",
    240 : "two hundred forty",
    241 : "two hundred forty-one",
    242 : "two hundred forty-two",
    243 : "two hundred forty-three",
    244 : "two hundred forty-four",
    245 : "two hundred forty-five",
    246 : "two hundred forty-six",
    247 : "two hundred forty-seven",
    248 : "two hundred forty-eight",
    249 : "two hundred forty-nine",
    250 : "two hundred fifty",
    251 : "two hundred fifty-one",
    252 : "two hundred fifty-two",
    253 : "two hundred fifty-three",
    254 : "two hundred fifty-four",
    255 : "two hundred fifty-five",
    256 : "two hundred fifty-six",
    257 : "two hundred fifty-seven",
    258 : "two hundred fifty-eight",
    259 : "two hundred fifty-nine",
    260 : "two hundred sixty",
    261 : "two hundred sixty-one",
    262 : "two hundred sixty-two",
    263 : "two hundred sixty-three",
    264 : "two hundred sixty-four",
    265 : "two hundred sixty-five",
    266 : "two hundred sixty-six",
    267 : "two hundred sixty-seven",
    268 : "two hundred sixty-eight",
    269 : "two hundred sixty-nine",
    270 : "two hundred seventy",
    271 : "two hundred seventy-one",
    272 : "two hundred seventy-two",
    273 : "two hundred seventy-three",
    274 : "two hundred seventy-four",
    275 : "two hundred seventy-five",
    276 : "two hundred seventy-six",
    277 : "two hundred seventy-seven",
    278 : "two hundred seventy-eight",
    279 : "two hundred seventy-nine",
    280 : "two hundred eighty",
    281 : "two hundred eighty-one",
    282 : "two hundred eighty-two",
    283 : "two hundred eighty-three",
    284 : "two hundred eighty-four",
    285 : "two hundred eighty-five",
    286 : "two hundred eighty-six",
    287 : "two hundred eighty-seven",
    288 : "two hundred eighty-eight",
    289 : "two hundred eighty-nine",
    290 : "two hundred ninety",
    291 : "two hundred ninety-one",
    292 : "two hundred ninety-two",
    293 : "two hundred ninety-three",
    294 : "two hundred ninety-four",
    295 : "two hundred ninety-five",
    296 : "two hundred ninety-six",
    297 : "two hundred ninety-seven",
    298 : "two hundred ninety-eight",
    299 : "two hundred ninety-nine",
    300 : "Three hundred",
    301 : "Three hundred one",
    302 : "Three hundred two",
    303 : "Three hundred three",
    304 : "Three hundred four",
    305 : "Three hundred five",
    306 : "Three hundred six",
    307 : "Three hundred seven",
    308 : "Three hundred eight",
    309 : "Three hundred nine",
    310 : "Three hundred ten",
    311 : "Three hundred eleven",
    312 : "Three hundred twelve",
    313 : "Three hundred thirteen",
    314 : "Three hundred foruteen",
    315 : "Three hundred fifteen",
    316 : "Three hundred sixteen",
    317 : "Three hundred seventeen",
    318 : "Three hundred eighteen",
    319 : "Three hundred nineteen",
    320 : "Three hundred twenty",
    321 : "Three hundred twenty-one",
    322 : "Three hundred twenty-two",
    323 : "Three hundred twenty-three",
    324 : "Three hundred twenty-four",
    325 : "Three hundred twenty-five",
    326 : "Three hundred twenty-six",
    327 : "Three hundred twenty-seven",
    328 : "Three hundred twenty-eight",
    329 : "Three hundred twenty-nine",
    330 : "Three hundred thirty",
    331 : "Three hundred thirty-one",
    332 : "Three hundred thirty-two",
    333 : "Three hundred thirty-three",
    334 : "Three hundred thirty-four",
    335 : "Three hundred thirty-five",
    336 : "Three hundred thirty-six",
    337 : "Three hundred thirty-seven",
    338 : "Three hundred thirty-eight",
    339 : "Three hundred thirty-nine",
    340 : "Three hundred forty",
    341 : "Three hundred forty-one",
    342 : "Three hundred forty-two",
    343 : "Three hundred forty-three",
    344 : "Three hundred forty-four",
    345 : "Three hundred forty-five",
    346 : "Three hundred forty-six",
    347 : "Three hundred forty-seven",
    348 : "Three hundred forty-eight",
    349 : "Three hundred forty-nine",
    350 : "Three hundred fifty",
    351 : "Three hundred fifty-one",
    352 : "Three hundred fifty-two",
    353 : "Three hundred fifty-three",
    354 : "Three hundred fifty-four",
    355 : "Three hundred fifty-five",
    356 : "Three hundred fifty-six",
    357 : "Three hundred fifty-seven",
    358 : "Three hundred fifty-eight",
    359 : "Three hundred fifty-nine",
    360 : "Three hundred sixty",
    361 : "Three hundred sixty-one",
    362 : "Three hundred sixty-two",
    363 : "Three hundred sixty-three",
    364 : "Three hundred sixty-four",
    365 : "Three hundred sixty-five",
    366 : "Three hundred sixty-six",
    367 : "Three hundred sixty-seven",
    368 : "Three hundred sixty-eight",
    369 : "Three hundred sixty-nine",
    370 : "Three hundred seventy",
    371 : "Three hundred seventy-one",
    372 : "Three hundred seventy-two",
    373 : "Three hundred seventy-three",
    374 : "Three hundred seventy-four",
    375 : "Three hundred seventy-five",
    376 : "Three hundred seventy-six",
    377 : "Three hundred seventy-seven",
    378 : "Three hundred seventy-eight",
    379 : "Three hundred seventy-nine",
    380 : "Three hundred eighty",
    381 : "Three hundred eighty-one",
    382 : "Three hundred eighty-two",
    383 : "Three hundred eighty-three",
    384 : "Three hundred eighty-four",
    385 : "Three hundred eighty-five",
    386 : "Three hundred eighty-six",
    387 : "Three hundred eighty-seven",
    388 : "Three hundred eighty-eight",
    389 : "Three hundred eighty-nine",
    390 : "Three hundred ninety",
    391 : "Three hundred ninety-one",
    392 : "Three hundred ninety-two",
    393 : "Three hundred ninety-three",
    394 : "Three hundred ninety-four",
    395 : "Three hundred ninety-five",
    396 : "Three hundred ninety-six",
    397 : "Three hundred ninety-seven",
    398 : "Three hundred ninety-eight",
    399 : "Three hundred ninety-nine",
    400 : "Four hundred",
    401 : "Four hundred one",
    402 : "Four hundred two",
    403 : "Four hundred three",
    404 : "Four hundred four",
    405 : "Four hundred five",
    406 : "Four hundred six",
    407 : "Four hundred seven",
    408 : "Four hundred eight",
    409 : "Four hundred nine",
    410 : "Four hundred ten",
    411 : "Four hundred eleven",
    412 : "Four hundred twelve",
    413 : "Four hundred thirteen",
    414 : "Four hundred fourteen",
    415 : "Four hundred fifteen",
    416 : "Four hundred sixteen",
    417 : "Four hundred seventeen",
    418 : "Four hundred eighteen",
    419 : "Four hundred nineteen",
    420 : "Four hundred twenty",
    421 : "Four hundred twenty-one",
    422 : "Four hundred twenty-two",
    423 : "Four hundred twenty-three",
    424 : "Four hundred twenty-four",
    425 : "Four hundred twenty-five",
    426 : "Four hundred twenty-six",
    427 : "Four hundred twenty-seven",
    428 : "Four hundred twenty-eight",
    429 : "Four hundred twenty-nine",
    430 : "Four hundred thirty",
    431 : "Four hundred thirty-one",
    432 : "Four hundred thirty-two",
    433 : "Four hundred thirty-three",
    434 : "Four hundred thirty-four",
    435 : "Four hundred thirty-five",
    436 : "Four hundred thirty-six",
    437 : "Four hundred thirty-seven",
    438 : "Four hundred thirty-eight",
    439 : "Four hundred thirty-nine",
    440 : "Four hundred forty",
    441 : "Four hundred forty-one",
    442 : "Four hundred forty-two",
    443 : "Four hundred forty-three",
    444 : "Four hundred forty-four",
    445 : "Four hundred forty-five",
    446 : "Four hundred forty-six",
    447 : "Four hundred forty-seven",
    448 : "Four hundred forty-eight",
    449 : "Four hundred forty-nine",
    450 : "Four hundred fifty",
    451 : "Four hundred fifty-one",
    452 : "Four hundred fifty-two",
    453 : "Four hundred fifty-three",
    454 : "Four hundred fifty-four",
    455 : "Four hundred fifty-five",
    456 : "Four hundred fifty-six",
    457 : "Four hundred fifty-seven",
    458 : "Four hundred fifty-eight",
    459 : "Four hundred fifty-nine",
    460 : "Four hundred sixty",
    461 : "Four hundred sixty-one",
    462 : "Four hundred sixty-two",
    463 : "Four hundred sixty-three",
    464 : "Four hundred sixty-four",
    465 : "Four hundred sixty-five",
    466 : "Four hundred sixty-six",
    467 : "Four hundred sixty-seven",
    468 : "Four hundred sixty-eight",
    469 : "Four hundred sixty-nine",
    470 : "Four hundred seventy",
    471 : "Four hundred seventy-one",
    472 : "Four hundred seventy-two",
    473 : "Four hundred seventy-three",
    474 : "Four hundred seventy-four",
    475 : "Four hundred seventy-five",
    476 : "Four hundred seventy-six",
    477 : "Four hundred seventy-seven",
    478 : "Four hundred seventy-eight",
    479 : "Four hundred seventy-nine",
    480 : "Four hundred eighty",
    481 : "Four hundred eighty-one",
    482 : "Four hundred eighty-two",
    483 : "Four hundred eighty-three",
    484 : "Four hundred eighty-four",
    485 : "Four hundred eighty-five",
    486 : "Four hundred eighty-six",
    487 : "Four hundred eighty-seven",
    488 : "Four hundred eighty-eight",
    489 : "Four hundred eighty-nine",
    490 : "Four hundred ninety",
    491 : "Four hundred ninety-one",
    492 : "Four hundred ninety-two",
    493 : "Four hundred ninety-three",
    494 : "Four hundred ninety-four",
    495 : "Four hundred ninety-five",
    496 : "Four hundred ninety-six",
    497 : "Four hundred ninety-seven",
    498 : "Four hundred ninety-eight",
    499 : "Four hundred ninety-nine",
    500 : "Five hundred",
    501 : "Five hundred one",
    502 : "Five hundred two",
    503 : "Five hundred three",
    504 : "Five hundred four",
    505 : "Five hundred five",
    506 : "Five hundred six",
    507 : "Five hundred seven",
    508 : "Five hundred eight",
    509 : "Five hundred nine",
    510 : "Five hundred ten",
    511 : "Five hundred eleven",
    512 : "Five hundred twelve",
    513 : "Five hundred thirteen",
    514 : "Five hundred foruteen",
    515 : "Five hundred fifteen",
    516 : "Five hundred sixteen",
    517 : "Five hundred seventeen",
    518 : "Five hundred eighteen",
    519 : "Five hundred nineteen",
    520 : "Five hundred twenty",
    521 : "Five hundred twenty-one",
    522 : "Five hundred twenty-two",
    523 : "Five hundred twenty-three",
    524 : "Five hundred twenty-four",
    525 : "Five hundred twenty-five",
    526 : "Five hundred twenty-six",
    527 : "Five hundred twenty-seven",
    528 : "Five hundred twenty-eight",
    529 : "Five hundred twenty-nine",
    530 : "Five hundred thirty",
    531 : "Five hundred thirty-one",
    532 : "Five hundred thirty-two",
    533 : "Five hundred thirty-three",
    534 : "Five hundred thirty-four",
    535 : "Five hundred thirty-five",
    536 : "Five hundred thirty-six",
    537 : "Five hundred thirty-seven",
    538 : "Five hundred thirty-eight",
    539 : "Five hundred thirty-nine",
    540 : "Five hundred forty",
    541 : "Five hundred forty-one",
    542 : "Five hundred forty-two",
    543 : "Five hundred forty-three",
    544 : "Five hundred forty-four",
    545 : "Five hundred forty-five",
    546 : "Five hundred forty-six",
    547 : "Five hundred forty-seven",
    548 : "Five hundred forty-eight",
    549 : "Five hundred forty-nine",
    550 : "Five hundred fifty",
    551 : "Five hundred fifty-one",
    552 : "Five hundred fifty-two",
    553 : "Five hundred fifty-three",
    554 : "Five hundred fifty-four",
    555 : "Five hundred fifty-five",
    556 : "Five hundred fifty-six",
    557 : "Five hundred fifty-seven",
    558 : "Five hundred fifty-eight",
    559 : "Five hundred fifty-nine",
    560 : "Five hundred sixty",
    561 : "Five hundred sixty-one",
    562 : "Five hundred sixty-two",
    563 : "Five hundred sixty-three",
    564 : "Five hundred sixty-four",
    565 : "Five hundred sixty-five",
    566 : "Five hundred sixty-six",
    567 : "Five hundred sixty-seven",
    568 : "Five hundred sixty-eight",
    569 : "Five hundred sixty-nine",
    570 : "Five hundred seventy",
    571 : "Five hundred seventy-one",
    572 : "Five hundred seventy-two",
    573 : "Five hundred seventy-three",
    574 : "Five hundred seventy-four",
    575 : "Five hundred seventy-five",
    576 : "Five hundred seventy-six",
    577 : "Five hundred seventy-seven",
    578 : "Five hundred seventy-eight",
    579 : "Five hundred seventy-nine",
    580 : "Five hundred eighty",
    581 : "Five hundred eighty-one",
    582 : "Five hundred eighty-two",
    583 : "Five hundred eighty-three",
    584 : "Five hundred eighty-four",
    585 : "Five hundred eighty-five",
    586 : "Five hundred eighty-six",
    587 : "Five hundred eighty-seven",
    588 : "Five hundred eighty-eight",
    589 : "Five hundred eighty-nine",
    590 : "Five hundred ninety",
    591 : "Five hundred ninety-one",
    592 : "Five hundred ninety-two",
    593 : "Five hundred ninety-three",
    594 : "Five hundred ninety-four",
    595 : "Five hundred ninety-five",
    596 : "Five hundred ninety-six",
    597 : "Five hundred ninety-seven",
    598 : "Five hundred ninety-eight",
    599 : "Five hundred ninety-nine",
    600 : "Six hundred",
    601 : "Six hundred one",
    602 : "Six hundred two",
    603 : "Six hundred three",
    604 : "Six hundred four",
    605 : "Six hundred five",
    606 : "Six hundred six",
    607 : "Six hundred seven",
    608 : "Six hundred eight",
    609 : "Six hundred nine",
    610 : "Six hundred ten",
    611 : "Six hundred eleven",
    612 : "Six hundred twelve",
    613 : "Six hundred thirteen",
    614 : "Six hundred foruteen",
    615 : "Six hundred fifteen",
    616 : "Six hundred sixteen",
    617 : "Six hundred seventeen",
    618 : "Six hundred eighteen",
    619 : "Six hundred nineteen",
    620 : "Six hundred twenty",
    621 : "Six hundred twenty-one",
    622 : "Six hundred twenty-two",
    623 : "Six hundred twenty-three",
    624 : "Six hundred twenty-four",
    625 : "Six hundred twenty-five",
    626 : "Six hundred twenty-six",
    627 : "Six hundred twenty-seven",
    628 : "Six hundred twenty-eight",
    629 : "Six hundred twenty-nine",
    630 : "Six hundred thirty",
    631 : "Six hundred thirty-one",
    632 : "Six hundred thirty-two",
    633 : "Six hundred thirty-three",
    634 : "Six hundred thirty-four",
    635 : "Six hundred thirty-five",
    636 : "Six hundred thirty-six",
    637 : "Six hundred thirty-seven",
    638 : "Six hundred thirty-eight",
    639 : "Six hundred thirty-nine",
    640 : "Six hundred forty",
    641 : "Six hundred forty-one",
    642 : "Six hundred forty-two",
    643 : "Six hundred forty-three",
    644 : "Six hundred forty-four",
    645 : "Six hundred forty-five",
    646 : "Six hundred forty-six",
    647 : "Six hundred forty-seven",
    648 : "Six hundred forty-eight",
    649 : "Six hundred forty-nine",
    650 : "Six hundred fifty",
    651 : "Six hundred fifty-one",
    652 : "Six hundred fifty-two",
    653 : "Six hundred fifty-three",
    654 : "Six hundred fifty-four",
    655 : "Six hundred fifty-five",
    656 : "Six hundred fifty-six",
    657 : "Six hundred fifty-seven",
    658 : "Six hundred fifty-eight",
    659 : "Six hundred fifty-nine",
    660 : "Six hundred sixty",
    661 : "Six hundred sixty-one",
    662 : "Six hundred sixty-two",
    663 : "Six hundred sixty-three",
    664 : "Six hundred sixty-four",
    665 : "Six hundred sixty-five",
    666 : "Six hundred sixty-six",
    667 : "Six hundred sixty-seven",
    668 : "Six hundred sixty-eight",
    669 : "Six hundred sixty-nine",
    670 : "Six hundred seventy",
    671 : "Six hundred seventy-one",
    672 : "Six hundred seventy-two",
    673 : "Six hundred seventy-three",
    674 : "Six hundred seventy-four",
    675 : "Six hundred seventy-five",
    676 : "Six hundred seventy-six",
    677 : "Six hundred seventy-seven",
    678 : "Six hundred seventy-eight",
    679 : "Six hundred seventy-nine",
    680 : "Six hundred eighty",
    681 : "Six hundred eighty-one",
    682 : "Six hundred eighty-two",
    683 : "Six hundred eighty-three",
    684 : "Six hundred eighty-four",
    685 : "Six hundred eighty-five",
    686 : "Six hundred eighty-six",
    687 : "Six hundred eighty-seven",
    688 : "Six hundred eighty-eight",
    689 : "Six hundred eighty-nine",
    690 : "Six hundred ninety",
    691 : "Six hundred ninety-one",
    692 : "Six hundred ninety-two",
    693 : "Six hundred ninety-three",
    694 : "Six hundred ninety-four",
    695 : "Six hundred ninety-five",
    696 : "Six hundred ninety-six",
    697 : "Six hundred ninety-seven",
    698 : "Six hundred ninety-eight",
    699 : "Six hundred ninety-nine",
    700 : "Seven hundred",
    701 : "Seven hundred one",
    702 : "Seven hundred two",
    703 : "Seven hundred three",
    704 : "Seven hundred four",
    705 : "Seven hundred five",
    706 : "Seven hundred six",
    707 : "Seven hundred seven",
    708 : "Seven hundred eight",
    709 : "Seven hundred nine",
    710 : "Seven hundred ten",
    711 : "Seven hundred eleven",
    712 : "Seven hundred twelve",
    713 : "Seven hundred thirteen",
    714 : "Seven hundred foruteen",
    715 : "Seven hundred fifteen",
    716 : "Seven hundred sixteen",
    717 : "Seven hundred seventeen",
    718 : "Seven hundred eighteen",
    719 : "Seven hundred nineteen",
    720 : "Seven hundred twenty",
    721 : "Seven hundred twenty-one",
    722 : "Seven hundred twenty-two",
    723 : "Seven hundred twenty-three",
    724 : "Seven hundred twenty-four",
    725 : "Seven hundred twenty-five",
    726 : "Seven hundred twenty-six",
    727 : "Seven hundred twenty-seven",
    728 : "Seven hundred twenty-eight",
    729 : "Seven hundred twenty-nine",
    730 : "Seven hundred thirty",
    731 : "Seven hundred thirty-one",
    732 : "Seven hundred thirty-two",
    733 : "Seven hundred thirty-three",
    734 : "Seven hundred thirty-four",
    735 : "Seven hundred thirty-five",
    736 : "Seven hundred thirty-six",
    737 : "Seven hundred thirty-seven",
    738 : "Seven hundred thirty-eight",
    739 : "Seven hundred thirty-nine",
    740 : "Seven hundred forty",
    741 : "Seven hundred forty-one",
    742 : "Seven hundred forty-two",
    743 : "Seven hundred forty-three",
    744 : "Seven hundred forty-four",
    745 : "Seven hundred forty-five",
    746 : "Seven hundred forty-six",
    747 : "Seven hundred forty-seven",
    748 : "Seven hundred forty-eight",
    749 : "Seven hundred forty-nine",
    750 : "Seven hundred fifty",
    751 : "Seven hundred fifty-one",
    752 : "Seven hundred fifty-two",
    753 : "Seven hundred fifty-three",
    754 : "Seven hundred fifty-four",
    755 : "Seven hundred fifty-five",
    756 : "Seven hundred fifty-six",
    757 : "Seven hundred fifty-seven",
    758 : "Seven hundred fifty-eight",
    759 : "Seven hundred fifty-nine",
    760 : "Seven hundred sixty",
    761 : "Seven hundred sixty-one",
    762 : "Seven hundred sixty-two",
    763 : "Seven hundred sixty-three",
    764 : "Seven hundred sixty-four",
    765 : "Seven hundred sixty-five",
    766 : "Seven hundred sixty-six",
    767 : "Seven hundred sixty-seven",
    768 : "Seven hundred sixty-eight",
    769 : "Seven hundred sixty-nine",
    770 : "Seven hundred seventy",
    771 : "Seven hundred seventy-one",
    772 : "Seven hundred seventy-two",
    773 : "Seven hundred seventy-three",
    774 : "Seven hundred seventy-four",
    775 : "Seven hundred seventy-five",
    776 : "Seven hundred seventy-six",
    777 : "Seven hundred seventy-seven",
    778 : "Seven hundred seventy-eight",
    779 : "Seven hundred seventy-nine",
    780 : "Seven hundred eighty",
    781 : "Seven hundred eighty-one",
    782 : "Seven hundred eighty-two",
    783 : "Seven hundred eighty-three",
    784 : "Seven hundred eighty-four",
    785 : "Seven hundred eighty-five",
    786 : "Seven hundred eighty-six",
    787 : "Seven hundred eighty-seven",
    788 : "Seven hundred eighty-eight",
    789 : "Seven hundred eighty-nine",
    790 : "Seven hundred ninety",
    791 : "Seven hundred ninety-one",
    792 : "Seven hundred ninety-two",
    793 : "Seven hundred ninety-three",
    794 : "Seven hundred ninety-four",
    795 : "Seven hundred ninety-five",
    796 : "Seven hundred ninety-six",
    797 : "Seven hundred ninety-seven",
    798 : "Seven hundred ninety-eight",
    799 : "Seven hundred ninety-nine",
    800 : "Eight hundred",
    801 : "Eight hundred one",
    802 : "Eight hundred two",
    803 : "Eight hundred three",
    804 : "Eight hundred four",
    805 : "Eight hundred five",
    806 : "Eight hundred six",
    807 : "Eight hundred seven",
    808 : "Eight hundred eight",
    809 : "Eight hundred nine",
    810 : "Eight hundred ten",
    811 : "Eight hundred eleven",
    812 : "Eight hundred twelve",
    813 : "Eight hundred thirteen",
    814 : "Eight hundred foruteen",
    815 : "Eight hundred fifteen",
    816 : "Eight hundred sixteen",
    817 : "Eight hundred seventeen",
    818 : "Eight hundred eighteen",
    819 : "Eight hundred nineteen",
    820 : "Eight hundred twenty",
    821 : "Eight hundred twenty-one",
    822 : "Eight hundred twenty-two",
    823 : "Eight hundred twenty-three",
    824 : "Eight hundred twenty-four",
    825 : "Eight hundred twenty-five",
    826 : "Eight hundred twenty-six",
    827 : "Eight hundred twenty-seven",
    828 : "Eight hundred twenty-eight",
    829 : "Eight hundred twenty-nine",
    830 : "Eight hundred thirty",
    831 : "Eight hundred thirty-one",
    832 : "Eight hundred thirty-two",
    833 : "Eight hundred thirty-three",
    834 : "Eight hundred thirty-four",
    835 : "Eight hundred thirty-five",
    836 : "Eight hundred thirty-six",
    837 : "Eight hundred thirty-seven",
    838 : "Eight hundred thirty-eight",
    839 : "Eight hundred thirty-nine",
    840 : "Eight hundred forty",
    841 : "Eight hundred forty-one",
    842 : "Eight hundred forty-two",
    843 : "Eight hundred forty-three",
    844 : "Eight hundred forty-four",
    845 : "Eight hundred forty-five",
    846 : "Eight hundred forty-six",
    847 : "Eight hundred forty-seven",
    848 : "Eight hundred forty-eight",
    849 : "Eight hundred forty-nine",
    850 : "Eight hundred fifty",
    851 : "Eight hundred fifty-one",
    852 : "Eight hundred fifty-two",
    853 : "Eight hundred fifty-three",
    854 : "Eight hundred fifty-four",
    855 : "Eight hundred fifty-five",
    856 : "Eight hundred fifty-six",
    857 : "Eight hundred fifty-seven",
    858 : "Eight hundred fifty-eight",
    859 : "Eight hundred fifty-nine",
    860 : "Eight hundred sixty",
    861 : "Eight hundred sixty-one",
    862 : "Eight hundred sixty-two",
    863 : "Eight hundred sixty-three",
    864 : "Eight hundred sixty-four",
    865 : "Eight hundred sixty-five",
    866 : "Eight hundred sixty-six",
    867 : "Eight hundred sixty-seven",
    868 : "Eight hundred sixty-eight",
    869 : "Eight hundred sixty-nine",
    870 : "Eight hundred seventy",
    871 : "Eight hundred seventy-one",
    872 : "Eight hundred seventy-two",
    873 : "Eight hundred seventy-three",
    874 : "Eight hundred seventy-four",
    875 : "Eight hundred seventy-five",
    876 : "Eight hundred seventy-six",
    877 : "Eight hundred seventy-seven",
    878 : "Eight hundred seventy-eight",
    879 : "Eight hundred seventy-nine",
    880 : "Eight hundred eighty",
    881 : "Eight hundred eighty-one",
    882 : "Eight hundred eighty-two",
    883 : "Eight hundred eighty-three",
    884 : "Eight hundred eighty-four",
    885 : "Eight hundred eighty-five",
    886 : "Eight hundred eighty-six",
    887 : "Eight hundred eighty-seven",
    888 : "Eight hundred eighty-eight",
    889 : "Eight hundred eighty-nine",
    890 : "Eight hundred ninety",
    891 : "Eight hundred ninety-one",
    892 : "Eight hundred ninety-two",
    893 : "Eight hundred ninety-three",
    894 : "Eight hundred ninety-four",
    895 : "Eight hundred ninety-five",
    896 : "Eight hundred ninety-six",
    897 : "Eight hundred ninety-seven",
    898 : "Eight hundred ninety-eight",
    899 : "Eight hundred ninety-nine",
    900 : "Nine hundred",
    901 : "Nine hundred one",
    902 : "Nine hundred two",
    903 : "Nine hundred three",
    904 : "Nine hundred four",
    905 : "Nine hundred five",
    906 : "Nine hundred six",
    907 : "Nine hundred seven",
    908 : "Nine hundred eight",
    909 : "Nine hundred nine",
    910 : "Nine hundred ten",
    911 : "Nine hundred eleven",
    912 : "Nine hundred twelve",
    913 : "Nine hundred thirteen",
    914 : "Nine hundred foruteen",
    915 : "Nine hundred fifteen",
    916 : "Nine hundred sixteen",
    917 : "Nine hundred seventeen",
    918 : "Nine hundred eighteen",
    919 : "Nine hundred nineteen",
    920 : "Nine hundred twenty",
    921 : "Nine hundred twenty-one",
    922 : "Nine hundred twenty-two",
    923 : "Nine hundred twenty-three",
    924 : "Nine hundred twenty-four",
    925 : "Nine hundred twenty-five",
    926 : "Nine hundred twenty-six",
    927 : "Nine hundred twenty-seven",
    928 : "Nine hundred twenty-eight",
    929 : "Nine hundred twenty-nine",
    930 : "Nine hundred thirty",
    931 : "Nine hundred thirty-one",
    932 : "Nine hundred thirty-two",
    933 : "Nine hundred thirty-three",
    934 : "Nine hundred thirty-four",
    935 : "Nine hundred thirty-five",
    936 : "Nine hundred thirty-six",
    937 : "Nine hundred thirty-seven",
    938 : "Nine hundred thirty-eight",
    939 : "Nine hundred thirty-nine",
    940 : "Nine hundred forty",
    941 : "Nine hundred forty-one",
    942 : "Nine hundred forty-two",
    943 : "Nine hundred forty-three",
    944 : "Nine hundred forty-four",
    945 : "Nine hundred forty-five",
    946 : "Nine hundred forty-six",
    947 : "Nine hundred forty-seven",
    948 : "Nine hundred forty-eight",
    949 : "Nine hundred forty-nine",
    950 : "Nine hundred fifty",
    951 : "Nine hundred fifty-one",
    952 : "Nine hundred fifty-two",
    953 : "Nine hundred fifty-three",
    954 : "Nine hundred fifty-four",
    955 : "Nine hundred fifty-five",
    956 : "Nine hundred fifty-six",
    957 : "Nine hundred fifty-seven",
    958 : "Nine hundred fifty-eight",
    959 : "Nine hundred fifty-nine",
    960 : "Nine hundred sixty",
    961 : "Nine hundred sixty-one",
    962 : "Nine hundred sixty-two",
    963 : "Nine hundred sixty-three",
    964 : "Nine hundred sixty-four",
    965 : "Nine hundred sixty-five",
    966 : "Nine hundred sixty-six",
    967 : "Nine hundred sixty-seven",
    968 : "Nine hundred sixty-eight",
    969 : "Nine hundred sixty-nine",
    970 : "Nine hundred seventy",
    971 : "Nine hundred seventy-one",
    972 : "Nine hundred seventy-two",
    973 : "Nine hundred seventy-three",
    974 : "Nine hundred seventy-four",
    975 : "Nine hundred seventy-five",
    976 : "Nine hundred seventy-six",
    977 : "Nine hundred seventy-seven",
    978 : "Nine hundred seventy-eight",
    979 : "Nine hundred seventy-nine",
    980 : "Nine hundred eighty",
    981 : "Nine hundred eighty-one",
    982 : "Nine hundred eighty-two",
    983 : "Nine hundred eighty-three",
    984 : "Nine hundred eighty-four",
    985 : "Nine hundred eighty-five",
    986 : "Nine hundred eighty-six",
    987 : "Nine hundred eighty-seven",
    988 : "Nine hundred eighty-eight",
    989 : "Nine hundred eighty-nine",
    990 : "Nine hundred ninety",
    991 : "Nine hundred ninety-one",
    992 : "Nine hundred ninety-two",
    993 : "Nine hundred ninety-three",
    994 : "Nine hundred ninety-four",
    995 : "Nine hundred ninety-five",
    996 : "Nine hundred ninety-six",
    997 : "Nine hundred ninety-seven",
    998 : "Nine hundred ninety-eight",
    999 : "Nine hundred ninety-nine",
    1000 : "one thousand",
}